Implemented matmul, improved reshape to handle singleton~1D Tensor conversions, improved testing coverage, Reduced comment clutter
pymatch/pymatch pull request #4
Opened 2023-10-18 04:04 UTC by SRM47

2023-10-18 16:35 UTC, anthonyjclark requested changes
Fantastic job!

2023-10-25 17:45 UTC, SRM47 commented on match/tensordata.py
> +                lhs.reshape_((1,) + lhs_shape)
The algorithm specified to prepend a 1 only if the shape of the las is 1-dimensional. I can try to see what happens otherwise.

2023-10-25 18:21 UTC, anthonyjclark requested changes
Just a couple of minor suggestions. I will accept the PR as is once you've let me know that you've seen the comments.

2023-10-25 18:21 UTC, anthonyjclark commented on match/tensordata.py
> +    def item(self) -> Union[int, float]:
Use the newer syntax if possible (I think it should be with 3.11)

```suggestion
    def item(self) -> int | float:
```

2023-10-25 18:21 UTC, anthonyjclark commented on match/tensordata.py
> +                lhs.reshape_((1,) + lhs_shape)
I meant should we use `lhs.reshape_(...)`, `lhs.reshape(...)`, or `lhs.view(...)`

2023-10-25 19:11 UTC, merged